function X = conj_N_points(N)
% Description: 
%   The conjugate axis points c^N_i are generated by a recursive algorithm
%
% Inputs: 
%   N : dimension
%
% Outputs:
%   X : sigma points on conjugate N axis, each row of the matrix X
%   corresponds to one sigma point, 2^NxN
% 
% Example: 
%   X = conj_N_points(3),

if(N == 1)
    X = [1; -1]; 
else
    D = conj_N_points(N - 1); 
    X(1:2^(N-1), 1) = 1; 
    X(1:2^(N-1), 2:N) = D; 
end
X(2^(N-1) + 1:2^N, 1:N) = -X(1:2^(N-1), 1:N); 
end