function X = conj_M_points(N, M)
% Description: 
%   The conjugate axis points c^M_i are generated by a recursive algorithm
%
% Inputs: 
%   N : dimension
%   M : order
%
% Outputs:
%   X : sigma points on conjugate M axis, each row of the matrix X
%   corresponds to one sigma point, 2^M(N choose M)xN
% 
% Example: 
%   X = conj_M_points(3, 2),

D = conj_N_points(M); 
C = nchoosek(1:N, M);    
A = zeros(2^M, N);   % 2M x N
X = zeros(2^M * nchoosek(N, M), N);
cnt = 1;                  
for i = 1:nchoosek(N,M) 
    A(:) = 0; 
    for j = 1:M
        A(:, C(i, j)) = D(:, j);
    end
    X(cnt : cnt + 2^M - 1, :) = A;
    cnt = cnt + 2^M;
end
end