function X = principal_points(N)
% Description: 
%   The principal axis points sigma_i can be easily generated by the matrix
%   [I, -I]^T, where I is the identity matrix of dimension NxN. 
%
% Inputs: 
%   N : dimension
%
% Outputs:
%   X : sigma points on principal axis, each row of the matrix X
%   corresponds to one sigma points, 2NxN
% 
% Example: 
%   X = principal_points(3),

X = nan(2 * N, N);
I = eye(N); 
X(1:N, 1:N) = I; 
X(N + 1:2*N, 1:N) = -I; 
end